package com.kjms.service.dto.requests;

public enum SubmittedListDetailType {
    SUBMITTED,
    CANCELLED,
    REVISION_REQUESTED,
    REVISION_REQUEST_ACCEPTED,
    REVISION_REQUEST_REJECTED,
    REVISION_REQUEST_ACCEPTED_BY_REVIEWER,
    REVISION_REQUEST_REJECTED_BY_REVIEWER,
    AUTHOR_UPLOAD,
    SUBMISSION_ACCEPTED_BY_REVIEWER,
    SUBMISSION_REJECTED_BY_REVIEWER,
}
