export interface IUser {
  id?: string,
  fullName?: string,
  email?: string,
  lastName?: string,
  countryId?: null,
  activated?: boolean,
  stateProvince?: string,
  mobileNumber?: string,
  phoneCode?: string,
  invitedUser?: null,
  createdByUserId?:null,
  createdDate?:Date |null,
  lastModifiedDate?:Date |null,
  lastModifiedByUserId?: string,
}
export const defaultValue: Readonly<IUser> = {
  id: null,
  fullName: '',
  email: '',
  lastName: '',
  countryId: null,
  activated: true,
  stateProvince: '',
  mobileNumber: '',
  phoneCode: '',
  invitedUser: null,
  createdByUserId:null,
  createdDate:null,
  lastModifiedDate: null,
  lastModifiedByUserId: '',
};
